# ---------------------------------------------------------
# NB! Ikke bruk de norske bokstavene i kommentarer her !!!
# ---------------------------------------------------------

# Context root. Alle stier/mappings er relativt til denne.
server.servlet.context-path=/bokliste

